### ISSUE TITLE
Unordered list item bullets misaligned in all prose sizes

### ISSUE THREAD

**Issue by riverar** [tailwindlabs/tailwindcss-typography#117]
![](https://user-images.githubusercontent.com/475132/103040434-44c98d00-4528-11eb-976f-6f51d0383478.png)
Example: List item rendered in `prose-2xl`
https://jsfiddle.net/agkoLt8x/15/

**Comment by adamwathan** [comment]
Hey! They are centered but compared to the line-height:

![image](https://user-images.githubusercontent.com/4323180/103101802-4a39dc80-45e7-11eb-8d1d-2de6f7819942.png)

I think this is basically all we can really do, because different fonts have different rendered character sizes even at the same font-size/line-height.

No plans to adjust this currently but you can tweak this in your own projects using the customization API 👍🏻
