### ISSUE TITLE
Why not use ::marker pseudo-element on lists?

### ISSUE THREAD

**Issue by drdogbot7** [tailwindlabs/tailwindcss-typography#131]
::marker is pretty well supported and will certainly become the standard way to customize bullets.

I'm wondering if there's a reason for using ::before here.  Is it for the sake of IE11?

**Comment by neupauer** [comment]
Hi, I like your idea, but I think right now it is not possible to style it with `::marker`.

Because the `tailwindcss` itself (not the `tailwindcss-typography`) sets the `list-style` to `none`, there is no way in CSS to set it back to default browser behavior (If I'm not wrong). Values like `initial` or `revert` do not work this way.

To use `::marker` is necessary to set `ol` list style type to something (`decimal`, `lower-alpha`, ...) but there is no such value that would respect the `ol` `type` attribute (I think that is why you are pointing at that issue).

Fixing it in the `tailwindcss` would introduce a breaking change.

**Comment by drdogbot7** [comment]
My thinking was just that it would simplify the list styling a bit compared to using the ::before pseudo element.  The benefit is that this could make it easier for users to customize.

**Comment by neumannjan** [comment]
Additional issue with this is that if you have a floating image to the left of the bullet list, the bullets do not stay next to the text but are all the way to the left, obsured by the image. This is definitely quite broken.

**Comment by dstroot** [comment]
Came here to seek understanding of this behavior "Because the tailwindcss itself (not the tailwindcss-typography) sets the list-style to none, there is no way in CSS to set it back to default browser behavior."

This just seems wrong to me - why deliberately break standard behavior?  I am trying to implement light/dark mode and use Typography and I am finding all these strange issues - now I have style the bullet or number separately.  Not sure what was gained.

**Comment by BlackGlory** [comment]
`::marker` has different margins on Firefox and Chrome, and cannot be normalized via CSS.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

We are currently using `::marker` already so going to close this 👍
