### ISSUE TITLE
How to disable a style?

### ISSUE THREAD

**Issue by eduardoarandah** [tailwindlabs/tailwindcss-typography#134]
**Problem:**

When the user wants to add a link with some style, like a button `.mybtn` turns out that class `.prose a` is taking precedence so `.mybtn` isn't applied correctly. 

Example `.prose a` is blue but `a.mybtn` has a dark background and white text

Example:

![image](https://user-images.githubusercontent.com/4065733/105274398-b82fe000-5b62-11eb-9f51-481a5da9e413.png)

![image](https://user-images.githubusercontent.com/4065733/105274450-d8f83580-5b62-11eb-84fc-e659b3d7279b.png)

**Attempted solution**

I tried disabling styling with null or empty

```
module.exports = {
  theme: {
    typography: {
      default: {
        css: {
          a: {
            color: null,
            '&:hover': {
              color: '',
            },
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography')({
      modifiers: ['lg'],
    }),
  ],
};

```

**Is there a known solution?**

**Comment by paul-crashley** [comment]
This is the exact same reason I'm here. It's very frustrating. I can't even override it using Tailwind styles on the a tag or applying many styles, e.g.

`@apply prose lg:prose-lg text-white lg:text-white`

I don't want to do it in the tailwind config either, because it's a one-off, I don't want the change globally.

Why is typography dictating text color anyway?

**Comment by troelsfr** [comment]
I am having the exact same issue.

**Comment by eduardoarandah** [comment]
One quick solution I’ve found is copy pasting prose css into my css making sure it doesn’t take precedence.

**Comment by DynamiteGoesBoom** [comment]
I was having a similar problem with `prose` taking precedence in my CSS. I kind of got around the issue by creating a new object in my tailwind config and over wrote some of the defaults like so:

```
'aside': {
                css: {
                    'h3': {
                        color: theme('colors.white.100'),
                        fontSize: theme('fontSize.2xl'),
                        fontWeight: '400',
                        marginTop: false,
                        marginBottom: false,
                        lineHeight: false,
                    },
                    'ul > li': {
                        paddingLeft: '0',
                    },
                    'ul > li::before': {
                        'content': 'none',
                    },
                }
            },
```

Of course it'll all depend on what you need to override from the [default](https://github.com/tailwindlabs/tailwindcss-typography/blob/master/src/styles.js) but hopefully this helps someone!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your issue!
Much appreciated! 🙏

Your idea of using `null` is correct, however you are missing a few things. When you put the `typography` config directly in the `theme` section, then you have to provide "everything". To avoid that put it in the `theme.extend` block. Next, you also have to use `DEFAULT` instead of `default`.

Here is a working example: https://play.tailwindcss.com/VpBfkwKt7w?file=config

**Comment by robinmetral** [comment]
Should we document this along with the other examples in the README? I also started by duplicating my styles in `theme.typography` before thinking, "there must be a better way" and checking the issues

**Comment by miljkovic5** [comment]
@RobinMalfait Could you please include this in the documentation, that if we want to disable a specific style, we should set `null` (if this approach is still valid)?
