### ISSUE TITLE
How to customize H tag in combination with anchor tag?

### ISSUE THREAD

**Issue by kaylumah** [tailwindlabs/tailwindcss-typography#149]
Hi,

Love this plugin, especially that I can use it in combination with markdown that I have little to no control over, especially with regard to classes that are applied.

Not sure if an issue is right way to ask this, but I hope I can get some pointers.

Like many blogs/websites I like to be able to create clickable / shareable H2-H6s, and was able to customize the markdown renderer to produce the following sample:

```html
<h2 id="lets-get-started"><a href="#lets-get-started">Let’s get started!</a></h2>
```

Because it is now a wrapper anchor link it automatically adds an underline but I did not figure out yet how to disable that.

The more intressting part I think is how to add a symbol / icon on hover. For example like https://tailwindcss.com/docs/functions-and-directives#variants does. 

Looking at the corrseponding code https://github.com/tailwindlabs/tailwindcss.com/search?q=after%3Ahash. I can see that it is done by adding custom css and selectors. Instead of using typography.
Since I have limited options controlling the css I was hoping this kind of behaviour is also possible using typography

Any pointers are greatly appreciated 

Thanks
Max

**Comment by simonswiss** [comment]
Hey!

Sorry for the very long time with no response here. The recently launched v0.5 of the Typography plugin makes it easier to override things, since the selectors used to style the `prose` blocks are all flat (no nested selectors that increase specificity).

One way that would work here would be to simply add a `not-italic` class to the `a` tag directly. Here's an example:

https://play.tailwindcss.com/Bzat1fnwzN

In this example, I have also implemented a `#` symbol on hover (the position/styling of it is up to you, but this will show you how you can use the `group-hover` variant to apply styles to a child element (the `span` with the symbol) when a parent element (the `a` tag) is hovered.

Hope it helps!

Going to close this issue. If you have more questions, a better place to ask those is the Tailwind CSS GitHub discussions:

https://github.com/tailwindlabs/tailwindcss/discussions

**Comment by frank-laemmer** [comment]
I stumbled across this as well. My Tailwind Typography use case is to have some plugin/cms to create HTML from markdown. So instead of utility style verbose CSS classes markup, Typography enables good old cascading style sheets. 

I have no control about the inner markup of the headline anchor tag that is going to get created (by my plugin/CMS). Here is markup from a GitHub README :

```html
<h2 tabindex="-1" dir="auto">
  <a id="user-content-demos" class="anchor" aria-hidden="true" href="#demos"><svg in here /></a>
  Demos
</h2>
```

Other systems will create other markup. I guess some very verbose override will make it work anyhow.
