### ISSUE TITLE
Prose class not generated

### ISSUE THREAD

**Issue by jryd** [tailwindlabs/tailwindcss-typography#159]
### What version of @tailwindcss/typography are you using?

0.2

### What version of Node.js are you using?

13.12.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS Big Sur

### Reproduction repository

https://www.loom.com/share/b78934733b074ece9f45ace6c2b5cf4f

We're in the midst of upgrading a legacy project from a mix of Bootstrap and Tailwind 0.7x.

We've currently upgraded to Tailwind 1.9.x and wish to use the Tailwind Typography plugin to allow us to get rid of some of the styling applied by Bootstrap.

Given we're using Tailwind 1.9, it seems 0.2.0 is the appropriate Typography plugin version.

I've installed this with `npm install --save @tailwindcss/typography@0.2.0`.

I've updated our Tailwind config file to add the plugin:

```
module.exports = {
  theme: {
    extend: {
      // Some custom colours etc here
    },
  },
  variants: { cursor: ['responsive', 'hover'], opacity: ['responsive', 'hover'] },
  plugins: [
    // eslint-disable-next-line
    require('@tailwindcss/typography'),
  ],
};
```

We're using Laravel Mix to compile and the relevant lines are here
```
mix
  .sass('resources/assets/sass/app.scss', 'public/css').options({
    processCssUrls: false,
    postCss: [ require('tailwindcss') ],
  })
```

Our Javascript and CSS build successfully, however no `prose` classes exist in the generated output.

I cannot recreate this in Tailwind Play, nor can I share access to this specific repo. It very well may be something specific to this project, but I cannot for the life of me figure out what it is.
I've shared a video that walks through the issue and shows the classes not appearing in the generated output.

The rest of the Tailwind classes all generate successfully, it seems to just be the Typography classes that are missing.

**Comment by adamwathan** [comment]
Hey! Sorry we really need a reproduction to be able to sort this out since it appears to work as expected in Tailwind Play, and when I try to reproduce the issue locally.

Can you open a new issue if this is still a problem for you and include a minimal reproduction? Not your actual project, but something small that isolates this issue and shows it happening so we can easily troubleshoot. With that, we'll definitely be able to help.

Sorry if it feels hasty or inconsiderate to close — I get so many PRs and issues that the only way to possibly stay on top of things is to take decisive action on each one when I do get the chance to review, and ask for a new issue/PR if something is missing or needs to be changed. Otherwise things linger and stay open forever, since contributors often don't end up making any changes/updates so things just sit here piling up.
