### ISSUE TITLE
How to make latest version of Typography work in NuxtJS project 

### ISSUE THREAD

**Issue by garywoodfine** [tailwindlabs/tailwindcss-typography#161]
### What version of @tailwindcss/typography are you using?

v0.4.0

### What version of Node.js are you using?

15.10.0

### What browser are you using?

Brave, Chrome, Firefox

### What operating system are you using?

Linux (Ubuntu & PoPOS)

### Reproduction repository

https://github.com/Geek-I-Am/articles

It seems only version of "@tailwindcss/typography" that is functional with Nuxt is version 0.2.0

If I attempt to install any of the later version, the typography doesn't work.  I have upgraded all the other required tailwind modules for Nuxt to the their latest version.

I've run out of ideas of what I can try to resolve this issue, there don't seem to be any errors reported.
Any ideas as to how I could upgrade to the latest version of Typography on my Nuxt proejct?

**Comment by wellgoodthen** [comment]
I'm using 0.4.0 using Nuxt.js, but I had a heap of issues along the way.

Eventually I realised I'd installed Tailwindcss wrong, because Nuxt.js isn't compatible with postcss 8. You need to use [these installation instructions](https://tailwindcss.com/docs/installation#install-tailwind-via-npm).

I also had other problems from using node v16, which went away when I went back to using the LTS version.

**Comment by garywoodfine** [comment]
Thanks for comment.

I believe as of of the release [2.15 Nuxt.js](https://github.com/nuxt/nuxt.js/releases) it now has support for Postcss 8 and using the latest release of the  [Nuxt TailwindCSS module](https://github.com/nuxt-community/tailwindcss-module)  [version 4.0 +](https://github.com/nuxt-community/tailwindcss-module/releases/tag/v4.0.0) .

I have installed both these versions.

**Comment by desaintflorent** [comment]
I have the same problem, i just upgraded my project to the latest Nuxtjs v2.15.8 and @nuxtjs/tailwindcss 4.2.1 and using the latest version of @tailwindcss/typography doesn't work. I have to force v0.2.0 to be able to make it work.
Any idea on how to fix that ?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I just created a fresh project following our install instructions here: https://tailwindcss.com/docs/guides/nuxtjs
Then followed the instructions for installing the typography plugin here: https://tailwindcss.com/docs/typography-plugin

I made a repo for it as well so that you can see all the steps: https://github.com/RobinMalfait/nuxt-with-tailwindcss-and-typography/commits/main

The result looks like this:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/1834413/155341439-bd13adf8-fbd9-4ac5-aa85-48857e21fcf6.png">
