### ISSUE TITLE
[Bug] : unclear how to customize fontFamily properly

### ISSUE THREAD

**Issue by vladdu** [tailwindlabs/tailwindcss-typography#171]
### What version of @tailwindcss/typography are you using?

0.4.0

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome 

### What operating system are you using?

Windows

### Reproduction repository

N/A

### Describe your issue

The documentation doesn't say how to customize fontFamily, and the result with tailwindcss 2.1.0 is unexpected (and wrong).
I tried `fontFamily: theme('fontFamily.serif')`, but that outpults a "fontFamily: blabla" for each element, and the last is used, instead of the first.
I got advice to do either `fontFamily: theme('fontFamily.serif').join(",")`, or `"@apply font-serif":""` which give the right output, but then there are no quotes around names with spaces (and this looks like it happens even without the typography plugin, will write a ticket for that).

What would be the recommended way? I think it should be in the examples in the Readme file.

**Comment by ItalyPaleAle** [comment]
Literally just had the same issue, and the solution seems to be here: https://github.com/tailwindlabs/tailwindcss-typography/issues/14#issuecomment-658261095

In short:

- Put the `fontFamily` property in the `DEFAULT` object
- Use a closure: ``fontFamily: `${theme('fontFamily.serif')}` ``

**Comment by vladdu** [comment]
Thanks! I think the docs should mention that, as it's not self-evident.

**Comment by adamwathan** [comment]
Hey! Definitely planning to flesh out the customization docs more in the future, glad you were able to find a solution in the mean time.

The root cause of the issue is that the `theme` function just returns exactly what is in your theme object, so if your font family is defined as an array, it returns an array, and arrays of course aren't valid in CSS so you need to `join` the items in them. You don't need quotes around font family names typically for what it's worth, but when you do you just need to make sure to include the quotes when adding the custom font family:

```js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      fontFamily: {
        display: ['"Custom Font"'] // Notice the extra inner quotes
      }
    }
  }
}
```

Using a template literal will call `toString` on the array which joins it and adds commas so that works but kind of by chance. We can probably improve the behavior of the `theme` function to be smarter about this I think — the CSS version of the theme function is already smart about this and will join things for you. It's a breaking change though so will have to wait for Tailwind 3.0.
