### ISSUE TITLE
[Bug] : Long numbers are being shortened

### ISSUE THREAD

**Issue by dok42** [tailwindlabs/tailwindcss-typography#177]
### What version of @tailwindcss/typography are you using?

v0.4.0

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Edge, Firefox, Firefox Developer

### What operating system are you using?

Windows

### Describe your issue

In one of my markdown file I have a number composed by 11 digits.

For example, these
```
123456  
1234567  
1234567890
```

are being rendered like this
![Screenshot 2021-05-13 020927](https://user-images.githubusercontent.com/25151676/118059240-51903580-b390-11eb-8ab2-959e0873b958.jpg)

This number being a VAT number, it's important that is not truncated at 7 digits.

How can I avoid this ?

**Comment by simonswiss** [comment]
Hey!

Do you have a code example of this? Pretty hard to figure out what's happening based on a screenshot. 

I assume your VAT number is displayed in a `<code>` tag, based on the styling applied?

Are you able to share the rendered HTML markup?

**Comment by dok42** [comment]
Hello :) 
Actually I did put the VAT number inside a `<code>` tag so it is not going to be truncated.
If I do not use the code styling, the rendered number is being truncated at 7 digit.

I have to ask if I can share the code, but, it's a simple, very small, contact/society info page written in markdown.
The file is rendered ok in Markdown Monster, or VSCode (if this could be of any help).

My setup is a Sveltekit website, with Tailwindcss and MDSvex, with no customizations at all. 

The file containing the VAT number can be summarized as follows:
```
---
layout: blog
---

# Society Info

lorem ipsum blablabla..
VAT number: 12345678900
```

**Comment by adamwathan** [comment]
Hey! I can't seem to reproduce this:

https://play.tailwindcss.com/POYjsL7L8y

I'm going to close since I can't reproduce, but if it's still an issue can you create a new issue and include a separate project that reproduces it? Ideally we don't really want your full project anyways, just the absolute minimum necessary to reproduce.

_Sorry if it feels hasty or inconsiderate to close — I get so many PRs and issues that the only way to possibly stay on top of things is to take decisive action on each one when I do get the chance to review, and ask for a new issue/PR if something is missing or needs to be changed. Otherwise things linger and stay open forever, since contributors often don't end up making any changes/updates so things just sit here piling up. Thanks for understanding ❤️_

**Comment by dok42** [comment]
Nah no problems at all with closing ;). I perfectly understand.
As I'm using mdsvex, maybe the issue has something to do with that. I'll do some tests here locally and I'll let you know when I have better, more, informations ;).

While I'm here, THANK YOU for all your work with Tailwindcss, can't thank you and your team enough. ❤️
