### ISSUE TITLE
XL version customization not working completely

### ISSUE THREAD

**Issue by davidmles** [tailwindlabs/tailwindcss-typography#184]
### What version of @tailwindcss/typography are you using?

Tailwind Play

### What version of Node.js are you using?

Tailwind Play

### What browser are you using?

Safari

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/b4tjErT7ZV?file=config

### Describe your issue

I'm trying to customize the XL version, but it doesn't work completely.

Please, visit https://play.tailwindcss.com/b4tjErT7ZV?file=config

You will see a title and a text. Both are green, according to the DEFAULT overwritten config.

In order to see the XL customization applied, make the browser part 1024px wide. You'll see the title being red, but not the text. Why?

Another interesting thing: inspect the code using the developer tools of your browser, and change the "lg:prose-xl" part to "prose-xl". Now the colors are switched (title green, text red).

**Comment by adamwathan** [comment]
Hey @davidmles! The problem here is that responsive variants in Tailwind are always applied to the last class in a selector, so given a selector like this:

```
.prose-xl .custom-text { ... }
```

...when Tailwind tries to generate the responsive classes, it adds the breakpoints (like `lg:`) to the last class, resulting in this:

```
.prose-xl .lg\:custom-text { ... }
```

This is _usually_ what you want, and we did it this way so the `group-hover` variant behaves the way people expect, but once in a while it feels off, like what you're experiencing here.

One day I'd like to make this behavior more controllable by end users but unfortunately that's probably not going to happen in the immediate future.

For now, a workaround is to define your `custom-text` rule as `[class~="custom-text"]` — that is how we handle the built-in `lead` class for example:

https://play.tailwindcss.com/Gm4ku6YzBf?file=config

Hope that helps! Closing since this is a known/accepted limitation right now.
