### ISSUE TITLE
prose-a:hover:* is applied to the whole block in v0.5.0-alpha.3

### ISSUE THREAD

**Issue by seehat** [tailwindlabs/tailwindcss-typography#220]
### What version of @tailwindcss/typography are you using?

v0.5.0-alpha.3

### What version of Node.js are you using?

v17.0.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/seehat/tailwindcss-typography-hover-bug

### Describe your issue

When I use `prose-a:hover:text-yellow-500` I expect the hover state for the link only when hovering over the link. Instead it get's the state when hovering over the whole prose block. 

The rule is created for the whole block: 
```css
.prose-a\:hover\:text-yellow-500:hover :is(:where(a):not(:where([class~="not-prose"] *)))
```

**Comment by adamwathan** [comment]
Hey! This is by design, modifiers are resolved from the inside out kind of like function calls:

```
prose-a(hover(text-yellow-500))
```

To get the behavior you want, flip the modifiers:

```
<div class="hover:prose-a:text-yellow-500">
```

We debated reversing the order but then it becomes confusing for different modifiers, like `dark:group-hover:bg-red-500` would stop working and you'd have to write `group-hover:dark:bg-red-500` which feels wrong.

**Comment by seehat** [comment]
Wow this was fast! Thank you. It works.
