### ISSUE TITLE
H5 and H6 utility classes not available

### ISSUE THREAD

**Issue by espipj** [tailwindlabs/tailwindcss-typography#262]
### What version of @tailwindcss/typography are you using?

0.5.2

### What version of Node.js are you using?

14

### What browser are you using?

Any

### What operating system are you using?

Any

### Reproduction repository

https://play.tailwindcss.com/ZRBfmIgeI4?layout=horizontal

### Describe your issue

`h5` and `h6` tags are not supported by the utility classes and they're native to HTML.

If I am given some guidance I might be able to submit a PR.

**Comment by adamwathan** [comment]
Hey! Yep this is by design, we just didn't include them because we had no idea what to do with them — the `h4` styles are already the same size as the body text so there's not really any great options for `h5` and `h6` level headings and increasing the size of everything else to accommodate such rarely used headings felt like the wrong trade-off.

No plans to add them by default but you can of course add custom styles for these in your own project if you need them 👍🏻

**Comment by benjaminpreiss** [comment]
@RobertCordes I forked this project to add support for `prose-h5:...` and `prose-h6:...`. Here is the link to the fork: https://github.com/benjaminpreiss/tailwindcss-typography .
