### ISSUE TITLE
`not-prose` not working for headlines

### ISSUE THREAD

**Issue by pReya** [tailwindlabs/tailwindcss-typography#265]
### What version of @tailwindcss/typography are you using?

v0.5.2

### What version of Node.js are you using?

v17.8.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/tAgSeuspPh

### Describe your issue

Applying `not-prose` to a heading inside a prose-container should reset the headline styles to look unstyled, or am I misunderstanding something?

```
<!-- Unstyled -->
<div class="mb-8">
  <h1>Hello</h1>
  <p>Some Text</p>
</div>

<!-- Prose -->
<div class="prose mb-8">
  <h1>Hello</h1>
  <p>Some Text</p>
</div>

<!-- Prose w/ not-prose headline -> Headline should look like it's unstyled, right? -->
<div class="prose">
  <h1 class="not-prose">Hello</h1>
  <p>Some Text</p>
</div>
```

Reproduction on Tailwind Play: https://play.tailwindcss.com/tAgSeuspPh

**Comment by adamwathan** [comment]
Hey! At the moment this is by design — you need to put `not-prose` on a container and move the `h1` inside of it:

https://play.tailwindcss.com/Tnm7cDPguR

If you think it would be really valuable to be able to put `not-prose` directly on an element, definitely [post a feature request](https://github.com/tailwindlabs/tailwindcss/discussions/new?category=ideas) with some supporting arguments and we can consider it in the future 👍

**Comment by pReya** [comment]
Thanks for the quick reply @adamwathan! I guess I misunderstood the documentation / did not read it carefully.
