### ISSUE TITLE
Missing prose-lg and other classes other than just prose-xl

### ISSUE THREAD

**Issue by ilabsllc** [tailwindlabs/tailwindcss-typography#272]
### What version of @tailwindcss/typography are you using?

0.5.2

### What version of Node.js are you using?

v18.3.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### Reproduction repository

NA

### Describe your issue

This has been reported by several other users who see this problem on their existing project, but when they create a new simple project they can't repo this.

I have an existing Next JS project where I am using tailwindcss. 

The only class available is prose-xl and I can't find any other prose- class. I am using it with the next JS project.

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}

So my question to the team here is how do I debug this to figure out what is causing this problem rather than try to migrate all the code to a new project. Any pointers to debug this would be helpful.

**Comment by adamwathan** [comment]
Hey! Reproduction is definitely "A" and not "NA" I'm afraid 😅 Can't help without a reproduction.

**Comment by ilabsllc** [comment]
My question isn't why it's not working. My question is how do you debug such issues. 

This has been reported by a few users before where it works fine in a brand new project, but when you try to add this to a larger existing project it does seem to break under some conditions. 

So again any suggestion to help me debug such issues would be appreciated and would be helpful later for someone else too.

**Comment by adamwathan** [comment]
Sorry I don’t have time to write a troubleshooting guide for you at the moment. The first things I would look for are an incorrect `content` configuration or the use of dynamic class names. Not much I can offer without seeing the code so again happy to help with the problem if you provide a reproduction.

Going to close since we reserve issues for bug reports rather than questions and no reproduction was provided but if you’d like help with troubleshooting I recommend opening a discussion in our main discussion area or joining our Discord, lots of people there who will help. If you’d like help with this specific problem please open a new issue but include a reproduction.
