### ISSUE TITLE
Undoing style by `not-prose` is not working in `legacy` target

### ISSUE THREAD

**Issue by Codpoe** [tailwindlabs/tailwindcss-typography#277]
### What version of @tailwindcss/typography are you using?

v0.5.4

### What version of Node.js are you using?

v16.15.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/Codpoe/tailwind-typography-reproduction

### Describe your issue

After setting `target` to `legacy`, undoing style with `not-prose` is not working as expected.

[#L125](https://github.com/tailwindlabs/tailwindcss-typography/blob/23e04c6bc4330a6b493fe3698be11ff287f4d7bc/src/index.js#L125)
Maybe the code here can't just return `selector` directly, or maybe we can add a new `target` to solve this problem?

**Comment by adamwathan** [comment]
Hey! Yeah this is one of the features you lose when using the `legacy` target — with that target we can't use `:where` in CSS since it's fairly modern, and that feature is necessary for `not-prose` support.

If you'd like to use `not-prose` you'll have to not use the `legacy` target and target only more modern browsers.

**Comment by Codpoe** [comment]
Thanks for your reply😃. And is there any problem if we generate such code in legacy mode？
```css
.prose h1:not([class~='not-prose'] *) {
    /* ... */
}
```
