### ISSUE TITLE
Prose links are not applying hover styles properly

### ISSUE THREAD

**Issue by MikesGlitch** [tailwindlabs/tailwindcss-typography#278]
### What version of @tailwindcss/typography are you using?

3.1.5

### What version of Node.js are you using?

16.15.1

### What browser are you using?

chrome

### What operating system are you using?

windows

### Reproduction repository

https://play.tailwindcss.com/kLgUHVNc0A

### Describe your issue

When prose container is setup with the following classes: 

`prose-a:no-underline prose-a:hover:underline`

I'd expect the links to have **no underline by default**, and an **underline to appear when hovering over the anchor links**.  

**The bug:**

![bug](https://user-images.githubusercontent.com/5285928/182895318-fe3cd83b-b9da-46bd-91ec-dcddb3ae1cc0.gif)

As you can see, the `prose-a:hover:underline`  applies when hovering over the PROSE container, not the anchor link.

**Comment by thecrypticace** [comment]
This happens because the order of the variants matters! :)

In the case of `prose-a:hover:underline` it targets the element containing the `prose-a:hover:underline` class as the thing being hovered. What you actually want is `hover:prose-a:underline` which targets the individual links. This is because the `prose-a` variant changes the selector from a single class selector to one that targets child elements and `hover` modifies whatever the last part of the "current" selector is. If it helps, variants are applied in right-to-left order and not left-to-right order. For most utility classes and variants this doesn't matter but in this case it does because of how and when the selector changes.

Here's an updated example with the change: https://play.tailwindcss.com/lLgk8eG7vw

**Comment by adamwathan** [comment]
Here’s the relevant docs in case it’s interesting to you: https://tailwindcss.com/docs/hover-focus-and-other-states#ordering-stacked-modifiers
