### ISSUE TITLE
`` in <code> tag render effect is missing

### ISSUE THREAD

**Issue by h0wardch3ng** [tailwindlabs/tailwindcss-typography#279]
### What version of @tailwindcss/typography are you using?

0.5.4

### What version of Node.js are you using?

16.16.0

### What browser are you using?

all broswer

### What operating system are you using?

all platform

### Reproduction repository

https://github.com/h0wardch3ng/tailwindcss-typography

### Describe your issue

![](https://tailwindcss.com/_next/static/media/typography-demo.a776b2a812a1ee4fc9e5fe9001d18d23.jpg)

In this image, `` in <code> tag render effect is missing

`Test測試123@#$`

<img width="265" alt="image" src="https://user-images.githubusercontent.com/2175497/184290860-7338faea-70d9-4a4d-8a17-1a01d9ddd7e8.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/2175497/184290932-ad07cda9-e0d6-4c85-9074-3e2a8d6086af.png">

<img width="288" alt="image" src="https://user-images.githubusercontent.com/2175497/184290979-6f80444d-d400-4cc6-8bd9-311bf34bdd9d.png">

Light and dark theme as example in github markdown editor.

**Comment by thecrypticace** [comment]
Hey, this is intentional. The Typography plugin uses a different code-block style than GitHub does. We add the backticks using `::before`, and `::after` pseudo elements and render it in a monospace font.

If you want an effect similar to GitHub you can customize your config to remove the backticks and give code blocks a background color by [customizing the css](https://tailwindcss.com/docs/typography-plugin#customizing-the-css) in your config file.

Here's an example of doing just that: https://play.tailwindcss.com/QDeuWBNAxv?file=config

**Comment by oyal** [comment]
> Hey, this is intentional. The Typography plugin uses a different code-block style than GitHub does. We add the backticks using `::before` and `::after` pseudo elements as well as render it in a monospace font.
> 
> If you want an effect similar to GitHub you can customize your config to remove the backticks and give code blocks a background color by [customizing the css](https://tailwindcss.com/docs/typography-plugin#customizing-the-css) in your config file.
> 
> Here's an example of doing just that: https://play.tailwindcss.com/QDeuWBNAxv?file=config

Thank you very much for solving my problem.
