### ISSUE TITLE
Prose class not generated when using SASS

### ISSUE THREAD

**Issue by azzamsa** [tailwindlabs/tailwindcss-typography#282]
### What version of @tailwindcss/typography are you using?

v0.5.4

### What version of Node.js are you using?

v18.7.0

### What browser are you using?

Firefox 103.0.2

### What operating system are you using?

Debian GNU/Linux 11 (bullseye)

### Reproduction repository

https://github.com/azzamsa/mwe/tree/tailwind-prose/src/js/eleventy

### Describe your issue

I thought the root cause was custom color, Turns out, the `prose` class doesn't generated when I migrate from CSS to SASS.

Before:

![image](https://user-images.githubusercontent.com/17734314/186531291-72de56d8-dd39-43a3-a88c-629770635926.png)

After moving to SASS in this commit: https://github.com/azzamsa/mwe/commit/57b730c78d66dd9a708946396b193813512ebac8

![image](https://user-images.githubusercontent.com/17734314/186531587-42cba3ba-4cd5-40dc-afc6-bb0ca166e48e.png)

Related:
- https://github.com/tailwindlabs/tailwindcss-typography/issues/159

**Comment by adamwathan** [comment]
Hey! This doesn't look Tailwind related, your entire stylesheet isn't loading at all because Eleventy is trying to import an SCSS file directly in the browser which won't work:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/4323180/186549333-955df711-f87c-49f3-9fbc-5fcc7ab27a02.png">

Changing it to `<link href="/styles/index.css">` instead of `scss` seems to work 👍

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/4323180/186549489-0f090286-e924-4d5b-8ea2-03cf38fddda3.png">

**Comment by azzamsa** [comment]
Finally, found the root cause.

Spent a valid day to figure it out. I want to introduce `prose` to my already huge blog. the class is not generated. So I created MWE. It works all the time with smaller code. So I begin removing everything in my blog to find the root cause. Turns out it is just one line change.

```diff
@@ -12,6 +12,6 @@ module.exports = {
       mono: ["Victor Mono"],
     },
-    plugins: [],
   },
+    plugins: [require("@tailwindcss/typography")],
 };
```

My `plugin` key was inside `theme` block for years, but TailwindCSS never complaints about  it. 
Do TailwindCSS has mechanism to validate the configuration, if this is the plan, I will open a ticket.

Thanks a lot for TailwindCSS.
