### ISSUE TITLE
Compilation fails using the prose class from 0.5.3

### ISSUE THREAD

**Issue by mike-healy** [tailwindlabs/tailwindcss-typography#285]
### What version of @tailwindcss/typography are you using?

0.5.3 and up

### What version of Node.js are you using?

16.13.1

### What browser are you using?

N/A

### What operating system are you using?

MacOS and Ubuntu 20

### Reproduction repository

https://github.com/mike-healy/_tailwind-typography-error

### Describe your issue

When defining an @​apply set which contains the `prose` class the output CSS file compiles successfully with @tailwindcss/typography 0.5.2

If you upgrade to `0.5.3` or newer (including `0.5.7`) the build will fail with an error pointing to that line of the source CSS file.
If you then remove the `prose` class from the list, it will again compile successfully with newer versions of the package.

The reproduction repo README has more details about how to see this error.
This repo is a simplified version of the [Tailwind Underscore starter theme for WordPress](https://github.com/gregsullivan/_tw)

@gregsullivan – I'm not sure if this is purely an issue with this package, or the way it's used in _tw.

**Comment by gregsullivan** [comment]
I don't think this one is related to Tailwind Typography; my memory is that the issue was connected to a post-3.1 Tailwind update. I think after I did the initial changes to _tw for Tailwind 3.1 and removed `postcss-import`, there was a change to how the Tailwind CLI handled imports, and that broke the variable on the first line here:

https://github.com/mike-healy/_tailwind-typography-error/blob/ef5e41ff10dd1f197ee55152b609eda3379720ce/tailwind/tailwind.css#L13-L15

Changing that line to this:

```css
$(post-content-selector) {
```

...should resolve the problem.

This is also fixed in _tw for newly generated themes.

Here is the relevant commit:

https://github.com/gregsullivan/_tw/commit/1c370a19c9fa2b65a7906ff0f2c4b9c53638ceb1

Hope that helps!

**Comment by mike-healy** [comment]
@gregsullivan Genius! Thank you
