### ISSUE TITLE
Wrong order of custom utilities and prose with variant

### ISSUE THREAD

**Issue by zipper** [tailwindlabs/tailwindcss-typography#312]
### What version of @tailwindcss/typography are you using?

0.5.9

### What version of Node.js are you using?

v18.13.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://play.tailwindcss.com/M87sUUxyWK

### Describe your issue

I have some property (color in example) defined in `.prose-lg`. `.prose-lg` is used with variant `md:`.  I also have a custom utility `.foo`, which also sets color. As the utility is inside `@layer utilities`, it should have the priority over what is defined in prose. But that is not what happens when variant is used. When using native Tailwind utility, it works as expected. Also when only `.prose` is used, it works as expcted. In the example above, all paragraphs should be red.

In the generated output, the utility indeed is _before_ the media query for lg prose, but it should be _after_, The media for lg prose is right between custom utilities and tailwind utilities.

**Comment by adamwathan** [comment]
Hey! This is by design, the CSS generated by Tailwind is generated in this order:

```
/* Base styles */
/* Component styles */
/* Utility styles */
/* Component variants */
/* Utility variants */
```

We did this because it felt surprising that if you added some component class to an element and made some tweak to it with a utility that there was no way to get the original component styles back at a different breakpoint.

For instance:

```
<button class="btn text-sm md:btn-lg">Save</button>
```

It seemed weird that `md:btn-lg` would not apply it's proper font size there because of a tweak we tried to make to the mobile styling.

So the solution here is to re-specify your override at the breakpoint:

```
<div class="prose mx-auto md:prose-lg">
  <p class="foo">This text is expected to be red.</p>

  <p class="text-red-500 md:text-red-500">This text is as expected red.</p>
</div>
```

Feels a bit weird in this case I agree but between the two choices it felt like the more useful approach. This is something I'm considering changing again in v4 for totally different reasons to be the way you expected it though, so we'll see what happens there. I feel like we had other good reasons for doing it this way but I looked quickly and can't find where I wrote about it at the time.

Either way hope that explanation is helpful.

**Comment by zipper** [comment]
This is unfortunate. The problem I have is, that Typography plugin uses `.prose > :last-child` to reset margins (with some `:where` but lets not think about specificity now). So I added my own utility, that is independent on `.prose` and, basically `:last-child`. There is therefore no class to be added to html.

I guess I may try to add the same into `@screen md`? Would that be automatically counted as variant utility (if inside correct layer)? Or is there a better way.

The thing is, that we have some components that are inside prose and we still want them to be styled as one. As the html structure might be complicated we wouldn't want to put prose class inside all its lets say divs.

Honestly inability to insert my CSS code in a very specific place with Tailwind is the most hard thing for me when using it.

**Comment by zipper** [comment]
Unfortunately, adding the same style into @screen md didn't help, beucase it is placed directly after the code without media, i.e. into `/* Utility styles */` instead of what I need - `/* Utility variants */`. How could I achieve that with `:last-child` CSS selector?
