### ISSUE TITLE
Links don't have a default hover state

### ISSUE THREAD

**Issue by mrleblanc101** [tailwindlabs/tailwindcss-typography#337]
### What version of @tailwindcss/typography are you using?

0.5.10

### What version of Node.js are you using?

20

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

.

### Describe your issue

Links should probably have a default hover state, either darken/lighten the color or remove the underline.
I suggest removing the underline on hover as this is the most accessible option for vision impaired user.

**Comment by mrleblanc101** [comment]
https://github.com/tailwindlabs/tailwindcss-typography/blob/8d133ec2b6787a21b5babbcc2e88e9b959958db7/src/styles.js#L1409

**Comment by adamwathan** [comment]
Hey! Yeah this is by design at least at the moment and not an oversight — generally think of hover states as progressive enhancement rather than required these days since they don't happen on touch devices.

If you'd like to add hover states in your own projects you do it either in your configuration, or using an extra class like this:

```html
<article class="prose hover:prose-links:text-blue-500">
  <!-- ... -->
</article>
```

Going to close since I don't see this one as a bug and we're not planning to really update this project before Tailwind CSS v4.0 but I appreciate the feedback regardless 👍  We're planning to dramatically rethink what this project is and how it works for Tailwind CSS v4.0 in the next few months so we'll probably revisit these styles at that point no matter what.

**Comment by mrleblanc101** [comment]
This is a bad default, I thought the point of Tailwind Typography was that you didn't really need to configure anything.
So now, the accessibility of website using this plugin is lowered unless the developer think about changing this bad default.
