### ISSUE TITLE
The rendered image height is incorrect.

### ISSUE THREAD

**Issue by jwcesign** [tailwindlabs/tailwindcss-typography#343]
### What version of @tailwindcss/typography are you using?

0.5.12

### What version of Node.js are you using?

v18.16.1

### What browser are you using?

chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/jwcesign/md-render

### Describe your issue

With the original official react-markdown demo(https://remarkjs.github.io/react-markdown/), it renders correct for : https://raw.githubusercontent.com/alist-org/alist/v3.33.0/README.md
![image](https://github.com/tailwindlabs/tailwindcss-typography/assets/19745536/51eb41c3-5a9c-4f72-b737-135f80bdd0fa)

But with my demo project, it does not work fine for the big log:
![image](https://github.com/tailwindlabs/tailwindcss-typography/assets/19745536/f9278d9c-6e49-46b0-b429-f44dce6b8419)

After I change from height to width, it works fine: https://github.com/alist-org/alist/pull/6282

**Comment by reinink** [comment]
Hey! So technically this isn't an issue with the Typography plugin, but rather it's being caused by the Preflight styles in Tailwind CSS:

https://github.com/tailwindlabs/tailwindcss/blob/b01283cc9b66cf830d87cbfe1fbb5ebb8561226a/src/css/preflight.css#L369-L377

This is something we might eventually change, as there has been discussion about this previously:

https://github.com/tailwindlabs/tailwindcss/issues/506
https://github.com/tailwindlabs/tailwindcss/pull/7742

Until then, one trick you can use to undo these Preflight styles is to use `revert-layer`:

```css
img {
  height: revert-layer;
}

```

Alternatively, you could also set an explicit hight for this image using a creative attribute selector — something like this:

```css
img[alt="logo"]{
  height: 100px;
}
```

Hope that helps! 👍
