### ISSUE TITLE
Feature request: Export rem and em functions for customization

### ISSUE THREAD

**Issue by beornf** [tailwindlabs/tailwindcss-typography#36]
To guarantee equality with existing padding/margin options I copied the `rem` and `em` functions into the `tailwind.config.js` file. These helper functions could be exported which would help in future proofing a few minor customizations i.e.
```js
const typography = require('@tailwindcss/typography')

'thead th': {
  paddingTop: typography.em(8, 14),
  paddingRight: typography.em(12, 14),
  paddingLeft: typography.em(12, 14),
}
```

Alternatively is it possible the `rem` and `em` functions could be referenced in the `theme` scope?

**Comment by ahaseeb04** [comment]
As a workaround you could just copy paste them directly inside your Tailwind config file?

**Comment by beornf** [comment]
Yeah I did that. Maybe being a bit pedantic that it doesn't follow the DRY principle.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

I think another interesting approach, instead of exposing those functions, is to use the values in your theme you already have:

```js
module.exports = {
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            'p': {
              '@apply pt-4 pb-3': ''
            },
            'li': {
              '@apply text-blue-500': ''
            }
          },
        },
      },
    },
  },
  variants: {},
  plugins: [require('@tailwindcss/typography')],
}
```

https://play.tailwindcss.com/vG246MlQ7D?file=config

It's not 100% elegant, but I think it is better to re-use values from your config compared to re-creating new values.
