### ISSUE TITLE
Prefix prose classes

### ISSUE THREAD

**Issue by jlarmstrongiv** [tailwindlabs/tailwindcss-typography#48]
I would like to use `prose` to style a rich text editor, like [draft.js](https://github.com/facebook/draft-js/tree/master/examples/draft-0-10-0/rich), but its styles are being overridden.  It would be great to be able to prefix prose with an id or multiple classes to ensure that `prose` has enough css specificity to style the editor.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

One thing you can do is use the `important: "#app"` for example: https://play.tailwindcss.com/4skJYf6Q10 the downside is that all of your tailwind classes now require this root `#app`. Read more about this here: https://tailwindcss.com/docs/configuration#selector-strategy

If you want to up the specificity *just* for the `.prose` class you could change the `className` option: https://play.tailwindcss.com/PpEms9OVwC?file=config

This might look a bit strange at first, however the `className` is without the `.` so this means if you want to attach an id to it, you have to do something like `prose#app.prose`. The reason why I also attached the last `#app.prose` in there, is because if you have modifiers (xs, sm, ...) it will attach it to the className. So with just `prose#app` this would become `.prose#app-xl` instead of `.prose#app.prose-xl`.

This has the added benefit that your specificity increases. If you don't want to deal with an id, and just up the specificity by using multiple classes, then you could use `className: 'prose.prose.some-other-class.prose'`. You can go as crazy as you want.
