### ISSUE TITLE
rowspan misaligning table data

### ISSUE THREAD

**Issue by RJFares** [tailwindlabs/tailwindcss-typography#63]
Toggling prose off displays correct data, but adding prose to the table class is making some misalignment in the "Dog" column, check code and screenshot below.

<div class="container p-8 m-1 border bg-gray-100 mx-auto">
<table class="prose prose-sm sm:prose lg:prose-lg xl:prose-2xl antialiased mx-auto">
<thead>
<tr>
<th>Owner</th>
<th>Dog</th>
<th>Breed</th>
<th>Dog Age</th>
</tr>
</thead>

<tbody>

<tr>
	<td rowspan="3">Alisha Langosh</td>
<td>Ivah</td>
<td>Chiwawa</td>
<td>3 years old</td>
</tr>
<tr>
<td>Ivy</td>
<td>Labrador</td>
<td>13 years old</td>
</tr>
<tr>
<td>Orlo</td>
<td>Labrador</td>
<td>5 years old</td>
</tr>
											<tr>
	<td rowspan="1">Berenice Gibson</td>
<td>Jenifer</td>
<td>Wolf</td>
<td>13 years old</td>
</tr>
				<tr>
	<td rowspan="2">Bradford Bernier</td>
<td>Bernard</td>
<td>Labrador</td>
<td>9 years old</td>
</tr>
<tr>
<td>Camron</td>
<td>Wolf</td>
<td>5 years old</td>
</tr>
				<tr>
	<td rowspan="5">Chesley Ankunding</td>
<td>Caleb</td>
<td>Labrador</td>
<td>6 years old</td>
</tr>
<tr>
<td>Hadley</td>
<td>Labrador</td>
<td>4 years old</td>
</tr>
<tr>
<td>Jovanny</td>
<td>Labrador</td>
<td>10 years old</td>
</tr>
<tr>
<td>Kamren</td>
<td>Wolf</td>
<td>13 years old</td>
</tr>
<tr>
<td>Magdalena</td>
<td>German Shepherd</td>
<td>10 years old</td>
</tr>

</tbody>
</table>
</div>

![Untitled](https://user-images.githubusercontent.com/15612814/90903405-8e696600-e3d6-11ea-805b-d45c35fde808.jpg)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is a very interesting use case. We are relying on some `:first-child` selectors. The idea is that each `td` has padding within *except* for the first & last td's. This allows you to have nicely aligned `td`'s on the outside. This is done so that when you have a borderless table on the outside that you don't have weird indents.

However, the `:first-child` selectors will apply to the first child on a DOM level, meaning that the non-indented `td`'s in your screenshot *are* the first child elements. But visually they are clearly not.

I don't know if we can fix this in a general way, however I tried to fix things for your specific use case:
https://play.tailwindcss.com/gXZPDQ8Xym?file=config

Does this help you? If not, then we can re-open this issue and see if we can find another solution!

**Comment by madwyn** [comment]
I'm also having this exact issue, but I'm not sure this use case is crazy.

I tested the above method, it works with the latest version.

However, it only work for `prose`, `prose-lg` and all others still have the same issue.
