### ISSUE TITLE
Target .prose (as opposed to .prose-lg or .prose.sm)

### ISSUE THREAD

**Issue by jensamunch** [tailwindlabs/tailwindcss-typography#67]
Hey, 

It's cool that we can target specific sizes e.g. 'prose-lg' (see below). But how do we target 'prose'? It can't be default so not sure what it would be?

```
module.exports = {
  plugins: [
    require('@tailwindcss/ui'),
    require('@tailwindcss/typography'),
  ],
  important: true,
  future: {
  },
  experimental: {
    uniformColorPalette: true,
  },
  theme: {
    typography: {
      default: {
        css: {
          color: '#1d1d1f',
          'h1, h2, h3': {
            fontWeight: '800',
          },
          p: {
            '&::before': {
              content: 'none !important',
            },
            '&::after': {
              content: 'none !important',
            },
          },
        },
      },
      lg: {
        css: {
          'blockquote': {
            fontSize: '1.5rem',
            fontWeight: '600',
          },
        },
      },
    },
```

**Comment by JakeNavith** [comment]
It actually seemed to work for me to do `prose prose-sm md:prose` to use `prose-sm` until `md:`, and which point it becomes base-size `prose`. Really interested in how they were able to achieve that 🤔.

Does that work for you?

**Comment by benji014628** [comment]
I don't understand the issue

**Comment by kwiat1990** [comment]
I can understand your problem as I tried to achieve the same and didn't know that with `lg: { css: { ... }}` I target only `.prose-lg` and not change default `.prose` class according to current breakpoint. Is this even possible to do direct in config?

**Comment by benji014628** [comment]
yes, it's like normal CSS in the config

**Comment by RobinMalfait** [comment]
Hey! Thank you for your issue!
Much appreciated! 🙏

By default we have a `.prose`, all the styles that relate to this one can be styled under the `typography: { DEFAULT: { css: {} } }` section.
For other modifiers like `xl`, those can be styled under the `typography: { xl: { css: {} } }` section.

The reason that we split it up like this, is because you can define a `className` as one of the options (which defaults to `prose`). A modifier will then look like `.{{className}}-{{modifier}}`.

So to answer your question, I am not sure what you mean by `It can't be default so not sure what it would be?` because that is one that references `.prose`.
Note: Make sure that you use `DEFAULT` and not `default` for newer versions.
